### ISSUE TITLE
Assign a SI_Project to a PSP_Project

### ISSUE THREAD

**Issue by dancameron** [SproutApps/sprout-invoices-project-panorama-integration#1]
Took me a while to figure out the interface but this looks good.

<img width="1213" alt="screen shot 2016-02-26 at 10 48 56 am" src="https://cloud.githubusercontent.com/assets/1413460/13361948/9b0b7dc4-dc76-11e5-89ae-26e279efa6c7.png">

**Comment by dancameron** [comment]
I used the SI API to replace the sql query.

**Comment by dancameron** [comment]
@3pointross I'm building out the issues and planning the development for the rest and I'm finding we approached this wrong. Instead of assigning a client to the project we should "associate" an SI project with the PSP project. That way we know the client and all invoices and estimates. 

That way when I build #2 it would be a lot more fluid for the customer and easier to develop.

I'd like to make this option that you've created a dropdown selection, since an PSProject is 1:1 to an SI project.

Can you make it a dropdown? Or do you think it should be 1:many?

**Comment by 3pointross** [comment]
@dancameron That makes a lot of sense and I agree 1:1 is the best approach. With clients I could see users setting up multiple divisions within the same company and needing to associate multiple clients to a single project. 

I can't think of a common use case where you'd want multiple SI projects associated with one PSP project. 

I'll add this to my queue.

**Comment by dancameron** [comment]
Forgot to commit what I already did... 011489804529cd9800f40d606c60324d8db1ddf7

**Comment by dancameron** [comment]
@3pointross I forgot to commit the work I did earlier but you can see that it already does projects in 011489804529cd9800f40d606c60324d8db1ddf7

So the only real thing you'll need to do for this is make a dropdown for the project selection...actually, I'm thinking we could just have that selection in the new meta-box for #2, that way it's not buried under access. What do you think about handling it that way?

**Comment by 3pointross** [comment]
After some thought I agree. My first reaction was to leave it in access since customers are used to managing project access in this tab -- but considering the rest of the integration will be managed in another meta box we might as well group them together. If users have trouble figuring it out we can always move it later.

On a related note, I missed this comment and already swapped out the field in access for a drop down of SI projects. I had to rewrite the meta query filter and access check regardless so we'll be able to use the changes I made.

**Comment by dancameron** [comment]
@3pointross Checkout #2. I need to know if you have a meta_box API, or you can simply create one for me to start the creation of the view.

We should most definitely make it a dropdown and only store the post_id, not the entire project object. 

Any questions let me know.

**Comment by 3pointross** [comment]
@dancameron Nope no meta_box API for Panorama. With that said, it probably makes more sense for you to use the SI API to create the metabox and drop down. Based on the number of projects some of my customers have we may want that to evolve into an autocomplete / search -- but I think a drop down will be fine to start.

**Comment by dancameron** [comment]
@3pointross This is done, it just needs to be cleaned up a bit. 

Check it out and let me know what you can do to help.

**Comment by dancameron** [comment]
Again, looks great.
