### ISSUE TITLE
Link an SI project with an PP project

### ISSUE THREAD

**Issue by dancameron** [SproutApps/sprout-invoices-project-panorama-integration#3]
a) couldn't do a replacement because of SI add-ons, like time tracking
b) marking this as future because I don't see why this part of the integration would matter to anyone. Either people are using PP for projects or they're not.

**Comment by dancameron** [comment]
This is already accounted for with #1.

I'll just need to build a dropdown from the SI project admin to update the PP Project record. @3pointross I'm guessing that it's just a meta_key that needs to be updated, `pspsi_projects`?

**Comment by 3pointross** [comment]
Yes `pspi_projects` just needs to store the `si_project` ID. Right now the entire post object is being stored so line 122 `pspi_check_access_on_post()` will need to be adjusted by dropping the `->ID` Do you want me to add the field to a new metabox or were you planning on handling that?
