### ISSUE TITLE
Release of Integration

### ISSUE THREAD

**Issue by dancameron** [SproutApps/sprout-invoices-project-panorama-integration#5]
Now that we're almost done, how do you want to plan the release?

Please remind me if I missed anything from our prior conversations:

@dancameron:
- [x] Release in Marketplace as free add-on
- [x] Write and publish blog post at https://sproutapps.co/news/ highlighting some of the key features of Project Panorama. This post will be emailed within the newsletter.
- [x] Develop some sort of messaging within the app about PP and the integration, location would be on the project admin and will link to new integration page on our site.
- [x] Provide discount url to @3pointross 
- [x] Provide review of  Sprout Invoices for @3pointross blog post

@3pointross:
- [x] Add to integrations page
- [x] Write and publish blog post at https://www.projectpanorama.com/blog/.
- [x] Newsletter email.
- [x] Develop some sort of messaging within the app about SI and the integration...
- [x] Provide discount url/code to @dancameron
- [x] Provide review of Project Panorama for @dancameron blog post

**Comment by 3pointross** [comment]
This all looks good to me! Only additional item to note is I'll send out a message to my e-mail lists as well.

Refresh my memory about the reviews, is the idea that we write an overview of our plugins for posting on each others blog? 

In terms of messaging, I'm thinking of putting a tab within settings called "Invoices" then when clicked would have a message and direct users to the integration on the PP site -- conditional on the integration not being active of course.

**Comment by dancameron** [comment]
> Refresh my memory about the reviews, is the idea that we write an overview of our plugins for posting on each others blog?

Just to make it easier for each of us to write the blog posts on our own sites I thought it would be easier for you/me to provide a review for our own products. That way I don't miss a key feature of PP and vise versa. Hope that makes sense.

> In terms of messaging, I'm thinking of putting a tab within settings called "Invoices"

That's excellent.

**Comment by dancameron** [comment]
This is what every pro user will see on their projects admin.

<img width="341" alt="screen shot 2016-03-23 at 4 38 52 pm" src="https://cloud.githubusercontent.com/assets/1413460/14004413/38a3e5d0-f117-11e5-8b9c-208db23fac2c.png">

Here's the discount url - http://sproutapps.co/sprout-invoices/?_si_d=project-panorama
You can use any url with that query string.

**Comment by 3pointross** [comment]
Looks great, I've added the tab as well 

<img src="https://api.monosnap.com/rpc/file/download?id=2Kb1NBF6pMfcrvjdx59XN5ytNfvl94">

Here's a discount url http://www.projectpanorama.com/sproutcustomer/ which applies a coupon code of "sproutcustomer" 

I'm going to start working on the release and review, I should have them ready early next week.

**Comment by dancameron** [comment]
No rush, it's spring break next week for us so I'm on vacation with the
family. Lets try to do the announcement that next week though and I'll try
to complete my list next week.

**Comment by 3pointross** [comment]
Works for me, enjoy your vacation!

**Comment by 3pointross** [comment]
Review attached with markup. You should be able to just copy and paste it and go, I uploaded the images to the PP server to make it easier to post.

[project-panorama-review.txt](https://github.com/SproutApps/sprout-invoices-project-panorama-integration/files/200197/project-panorama-review.txt)

**Comment by dancameron** [comment]
This is very good. I'll get you the same this coming week while I'm at
microconf.

**Comment by dancameron** [comment]
I need to push this todo on Monday, sorry for the delay.

On Sat, Apr 2, 2016 at 8:37 PM Daniel Cameron dan@sproutventure.com wrote:

> This is very good. I'll get you the same this coming week while I'm at
> microconf.
> 
> On Fri, Apr 1, 2016 at 12:12 PM Ross Johnson notifications@github.com
> wrote:
> 
> > Review attached with markup. You should be able to just copy and paste it
> > and go, I uploaded the images to the PP server to make it easier to post.
> > 
> > project-panorama-review.txt
> > https://github.com/SproutApps/sprout-invoices-project-panorama-integration/files/200197/project-panorama-review.txt
> > 
> > —
> > You are receiving this because you were assigned.
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/SproutApps/sprout-invoices-project-panorama-integration/issues/5#issuecomment-204528097
> > 
> > ## 
> > 
> > Typos sent from my iPhone.

## 

Typos sent from my iPhone.

**Comment by 3pointross** [comment]
No problem, I'm not in a huge rush -- plenty of support to keep me busy in the meantime :+1:

**Comment by dancameron** [comment]
Here's your post.
https://gist.github.com/dancameron/afc255be8e67b8e3cdc6cdf794802af7

I got stuck at the end because I didn't know how you wanted to close it out. 

After lunch today I'm going to publish the edited post you gave me and release the add-on. Unless you want me to hold off. Whenever you get around to publishing yours (hopefully by mid this week) let me know.

Thanks!

**Comment by dancameron** [comment]
Published - https://sproutapps.co/news/project-management-project-panorama-sprout-invoices/

Add-on - https://sproutapps.co/marketplace/project-management-project-panorama/

It will go out to all the subscribers tomorrow am.

**Comment by 3pointross** [comment]
Awesome!

Published - https://www.projectpanorama.com/send-invoices-collect-payments-sprout-invoices-project-panorama/
Add-on - https://www.projectpanorama.com/add-ons/sprout-invoices/

Working on a newsletter this week that will focus on the integration as well.

I noticed that the PP link at the bottom of the add-on page links to the lite version but references the discount for SI users but I think it's supposed to link to http://www.projectpanorama.com/sproutcustomer/

The version of PP with the admin link went live late last week, I'm going to update it and add a second link to the add-on which will go out this week as well.

Cheers
-Ross

**Comment by dancameron** [comment]
Excellent.

Good catch on the link.
